apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prowlarr
resources:
  - namespace.yaml
  - config-pv.yaml
  - config-pvc.yaml
  - custom-cont-init-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob-rbac.yaml
  - cronjob.yaml
