apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-config-pv
spec:
  capacity:
    storage: 1Gi # Adjust as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/appdata/navidrome
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-basalt
