apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-basalt
      containers:
        - name: navidrome
          image: deluan/navidrome:latest
          env:
            - name: ND_LASTFM_APIKEY
              value: "af0e77858a2da6dece27f69af333c622"
            - name: ND_LASTFM_SECRET
              value: "878e939c8ff4eb3f129ed97f9639cc49"
          ports:
            - containerPort: 4533
              protocol: TCP
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: navidrome-config
              mountPath: /data
            - name: navidrome-music
              mountPath: /music
              readOnly: true
      volumes:
        - name: navidrome-config
          persistentVolumeClaim:
            claimName: navidrome-config
        - name: navidrome-music
          nfs:
            server: 192.168.1.126
            path: /mnt/user/Media/Music
