apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - config-pv.yaml
  - config-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
  - ubuntu-pod.yaml
