apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizarr
  template:
    metadata:
      labels:
        app: wizarr
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-basalt
      containers:
        - name: wizarr
          image: ghcr.io/wizarrrr/wizarr:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "2"
            requests:
              memory: "0Gi"
              cpu: "0"
          ports:
            - containerPort: 5690
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5690
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5690
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: TZ
              value: "Europe/Paris"
          volumeMounts:
            - name: wizarr-config
              mountPath: /data
      volumes:
        - name: wizarr-config
          persistentVolumeClaim:
            claimName: wizarr-config
